
PLAY [XBET__NginxForward] ******************************************************

TASK [nginx_sync : Notify] *****************************************************
ok: [192.168.11.126] => {
    "msg": "Syncing XBET__NginxForward"
}

TASK [nginx_sync : include_vars] ***********************************************
ok: [192.168.11.126]

TASK [nginx_sync : Synchronizing Nginx] ****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: filedescriptor out of range in select()
failed: [192.168.11.126] (item=conf) => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --copy-links --archive '--rsh=/usr/bin/ssh -S none -o Port=2556 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' '--out-format=<<CHANGED>>%i %n%L' /srv/XBET__NginxForward/nginx/conf/ ''", "item": "conf", "msg": "filedescriptor out of range in select()", "rc": 257}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: filedescriptor out of range in select()
failed: [192.168.11.126] (item=conf.d) => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --copy-links --archive '--rsh=/usr/bin/ssh -S none -o Port=2556 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' '--out-format=<<CHANGED>>%i %n%L' /srv/XBET__NginxForward/nginx/conf.d/ ''", "item": "conf.d", "msg": "filedescriptor out of range in select()", "rc": 257}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: filedescriptor out of range in select()
failed: [192.168.11.126] (item=data) => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --copy-links --archive '--rsh=/usr/bin/ssh -S none -o Port=2556 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' '--out-format=<<CHANGED>>%i %n%L' /srv/XBET__NginxForward/nginx/data/ ''", "item": "data", "msg": "filedescriptor out of range in select()", "rc": 257}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: filedescriptor out of range in select()
failed: [192.168.11.126] (item=html) => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --copy-links --archive '--rsh=/usr/bin/ssh -S none -o Port=2556 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' '--out-format=<<CHANGED>>%i %n%L' /srv/XBET__NginxForward/nginx/html/ ''", "item": "html", "msg": "filedescriptor out of range in select()", "rc": 257}
	to retry, use: --limit @/ansible/nginx/site.retry

PLAY RECAP *********************************************************************
192.168.11.126             : ok=2    changed=0    unreachable=0    failed=1   


