2020-08-17 09:25:14,499 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2020-08-17 09:25:19,514 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2020-08-17 09:25:27,345 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2020-08-17 09:25:41,079 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2020-08-17 09:28:11,152 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2020-08-17 09:28:22,646 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2020-08-17 09:39:17,309 ERROR - Internal Server Error: /LEManager/renew
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/LEManager/views.py", line 88, in post
    proc =  LEManager_create_SSL(body['CN'],sub,process="RENEW")
  File "/app/argus_final/app/argus/LEManager/tasks.py", line 145, in LEManager_create_SSL
    x=LC.renew(domain)
  File "/app/argus_final/app/argus/LEManager/lib/LEmoria_controller.py", line 41, in renew
    rVal = requests.post('{0}{1}'.format(self.url, self.endpoints['renew']), data=json.dumps(body),timeout=self.timeout)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='10.167.12.191', port=13567): Max retries exceeded with url: /renew (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3467f65410>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2020-08-17 09:46:58,222 ERROR - Internal Server Error: /LEManager/renew
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/LEManager/views.py", line 88, in post
    proc =  LEManager_create_SSL(body['CN'],sub,process="RENEW")
  File "/app/argus_final/app/argus/LEManager/tasks.py", line 145, in LEManager_create_SSL
    x=LC.renew(domain)
  File "/app/argus_final/app/argus/LEManager/lib/LEmoria_controller.py", line 41, in renew
    rVal = requests.post('{0}{1}'.format(self.url, self.endpoints['renew']), data=json.dumps(body),timeout=self.timeout)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='10.167.12.191', port=13567): Max retries exceeded with url: /renew (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f346ccdd650>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2020-08-17 09:48:49,341 ERROR - Internal Server Error: /LEManager/renew
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/LEManager/views.py", line 88, in post
    proc =  LEManager_create_SSL(body['CN'],sub,process="RENEW")
  File "/app/argus_final/app/argus/LEManager/tasks.py", line 145, in LEManager_create_SSL
    x=LC.renew(domain)
  File "/app/argus_final/app/argus/LEManager/lib/LEmoria_controller.py", line 41, in renew
    rVal = requests.post('{0}{1}'.format(self.url, self.endpoints['renew']), data=json.dumps(body),timeout=self.timeout)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='10.167.12.191', port=13567): Max retries exceeded with url: /renew (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3467ec8210>: Failed to establish a new connection: [Errno 110] Connection timed out',))
