2021-03-15 21:22:18,035 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-15 22:05:07,731 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:07,190 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:12,917 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:27,305 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:42,571 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:47,358 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:52,711 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:18:57,404 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 08:30:21,760 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 367-368: ordinal not in range(128)
2021-03-16 08:46:57,047 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2021-03-16 08:47:19,824 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2021-03-16 08:47:42,809 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2021-03-16 08:48:05,761 DEBUG - (emilyn.delacruz) - Successfully loaded and updated table
2021-03-16 08:48:14,018 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2021-03-16 08:48:48,288 DEBUG - (leriza.muralla) - Successfully loaded and updated table
2021-03-16 09:30:14,450 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 09:30:18,787 ERROR - Internal Server Error: /esync/om-weixin_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-16 10:57:39,376 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 246-248: ordinal not in range(128)
2021-03-16 11:47:24,628 DEBUG - (james.cadelina) - Successfully loaded and updated table
2021-03-16 13:21:38,461 ERROR - Internal Server Error: /domains/ssladded
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view domains.views.add_sslchecker didn't return an HttpResponse object. It returned None instead.
2021-03-16 13:22:43,236 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-16 14:41:06,943 ERROR - Internal Server Error: /admin/domains/domain/金世豪新闻网.com/change/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/defaultfilters.py", line 47, in _dec
    args[0] = force_text(args[0])
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/encoding.py", line 80, in force_text
    s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
2021-03-16 17:28:00,525 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-16 20:17:16,930 ERROR - Internal Server Error: /vpn-manager/initialization/SSRinitlogs/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/app/argus/SSRCHECKER/views.py", line 229, in SSRinitlogs
    SSRsave().ssrlogs(str(request.user.username))
  File "/app/argus_final/app/argus/SSRCHECKER/process.py", line 2086, in ssrlogs
    PORT=ssrinfo['ssr_port'],
TypeError: string indices must be integers, not str
2021-03-16 20:39:12,975 ERROR - Internal Server Error: /domains/ssladded
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view domains.views.add_sslchecker didn't return an HttpResponse object. It returned None instead.
2021-03-16 23:34:30,873 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:46:04,512 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:47:13,302 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:47:19,900 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:47:53,164 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:48:58,823 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-16 23:49:09,404 DEBUG - (yroll.macalino) - Successfully loaded and updated table
2021-03-17 01:14:32,934 DEBUG - starting thread (client mode): 0xc6f76810L
2021-03-17 01:14:32,934 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 01:14:32,978 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-17 01:14:32,978 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-17 01:14:32,992 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 01:14:32,992 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-17 01:14:32,992 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-17 01:14:32,993 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 01:14:32,993 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 01:14:32,993 DEBUG - Compression agreed: none
2021-03-17 01:14:33,001 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-17 01:14:33,002 DEBUG - Switch to new keys ...
2021-03-17 01:14:33,035 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.16.4]:28032: 75d1c31170d6257e2001c1129928c81c
2021-03-17 01:14:33,037 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 01:14:33,195 DEBUG - userauth is OK
2021-03-17 01:14:38,258 INFO - Authentication (publickey) successful!
2021-03-17 01:14:38,264 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 01:14:38,657 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 01:14:38,698 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 01:14:38,698 DEBUG - Secsh channel 0 opened.
2021-03-17 01:14:38,711 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:14:38,727 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:14:38,728 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 01:14:38,738 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 01:14:38,739 DEBUG - Secsh channel 1 opened.
2021-03-17 01:14:38,751 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 01:14:55,336 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 01:14:55,338 DEBUG - [chan 1] EOF received (1)
2021-03-17 01:14:55,338 DEBUG - [chan 1] EOF sent (1)
2021-03-17 01:14:55,341 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 01:14:55,341 DEBUG - Secsh channel 2 opened.
2021-03-17 01:14:55,387 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 01:14:55,652 DEBUG - [chan 2] EOF received (2)
2021-03-17 01:14:55,652 DEBUG - [chan 2] EOF sent (2)
2021-03-17 01:14:55,654 DEBUG - EOF in transport thread
2021-03-17 01:15:11,794 DEBUG - starting thread (client mode): 0xc7189490L
2021-03-17 01:15:11,794 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 01:15:11,806 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 01:15:11,807 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 01:15:11,809 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 01:15:11,809 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 01:15:11,809 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 01:15:11,810 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 01:15:11,810 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 01:15:11,810 DEBUG - Compression agreed: none
2021-03-17 01:15:11,859 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 01:15:11,860 DEBUG - Switch to new keys ...
2021-03-17 01:15:11,862 DEBUG - Adding ssh-ed25519 host key for [185.135.72.41]:28032: de457f91d6cfe90b74a47af1263b21ec
2021-03-17 01:15:11,863 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 01:15:11,907 DEBUG - userauth is OK
2021-03-17 01:15:12,734 DEBUG - starting thread (client mode): 0xc768b6d0L
2021-03-17 01:15:12,735 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 01:15:12,751 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 01:15:12,752 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 01:15:12,755 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 01:15:12,755 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 01:15:12,755 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 01:15:12,755 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 01:15:12,755 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 01:15:12,756 DEBUG - Compression agreed: none
2021-03-17 01:15:12,805 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 01:15:12,805 DEBUG - Switch to new keys ...
2021-03-17 01:15:12,836 DEBUG - Adding ssh-ed25519 host key for [58.64.167.40]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-17 01:15:12,837 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 01:15:12,850 DEBUG - userauth is OK
2021-03-17 01:15:14,798 DEBUG - starting thread (client mode): 0xc588ead0L
2021-03-17 01:15:14,798 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 01:15:14,834 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 01:15:14,834 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 01:15:14,839 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 01:15:14,840 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 01:15:14,840 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 01:15:14,840 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 01:15:14,840 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 01:15:14,840 DEBUG - Compression agreed: none
2021-03-17 01:15:14,865 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 01:15:14,866 DEBUG - Switch to new keys ...
2021-03-17 01:15:14,899 DEBUG - Adding ssh-ed25519 host key for [46.8.198.2]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-17 01:15:14,900 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 01:15:14,912 DEBUG - userauth is OK
2021-03-17 01:15:16,941 INFO - Authentication (publickey) successful!
2021-03-17 01:15:16,966 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 01:15:16,969 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-17 01:15:16,969 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-17 01:15:16,969 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 01:15:17,013 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 01:15:17,013 DEBUG - Secsh channel 0 opened.
2021-03-17 01:15:17,036 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:17,043 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:17,044 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 01:15:17,046 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 01:15:17,047 DEBUG - Secsh channel 1 opened.
2021-03-17 01:15:17,056 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 01:15:27,531 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 01:15:27,532 INFO - Authentication (publickey) successful!
2021-03-17 01:15:27,533 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-17 01:15:27,533 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-17 01:15:27,533 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 01:15:27,533 INFO - Authentication (publickey) successful!
2021-03-17 01:15:27,534 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-17 01:15:27,534 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-17 01:15:27,534 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 01:15:27,535 DEBUG - [chan 1] EOF received (1)
2021-03-17 01:15:27,535 DEBUG - [chan 1] EOF sent (1)
2021-03-17 01:15:27,536 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 01:15:27,536 DEBUG - Secsh channel 2 opened.
2021-03-17 01:15:27,538 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 01:15:27,538 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 01:15:27,541 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 01:15:27,541 DEBUG - Secsh channel 0 opened.
2021-03-17 01:15:27,543 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 01:15:27,543 DEBUG - Secsh channel 0 opened.
2021-03-17 01:15:27,547 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:27,553 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:27,554 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 01:15:27,554 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:27,557 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 01:15:27,557 DEBUG - Secsh channel 1 opened.
2021-03-17 01:15:27,562 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 01:15:27,562 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 01:15:27,566 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 01:15:37,931 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 01:15:37,933 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 01:15:37,933 DEBUG - [chan 2] EOF received (2)
2021-03-17 01:15:37,933 DEBUG - [chan 2] EOF sent (2)
2021-03-17 01:15:37,934 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 01:15:37,934 DEBUG - Secsh channel 1 opened.
2021-03-17 01:15:37,935 DEBUG - [chan 1] EOF received (1)
2021-03-17 01:15:37,936 DEBUG - [chan 1] EOF sent (1)
2021-03-17 01:15:37,936 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 01:15:37,936 DEBUG - Secsh channel 2 opened.
2021-03-17 01:15:37,938 DEBUG - EOF in transport thread
2021-03-17 01:15:37,951 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 01:15:50,267 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 01:15:50,269 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 01:15:50,269 DEBUG - [chan 2] EOF received (2)
2021-03-17 01:15:50,270 DEBUG - [chan 2] EOF sent (2)
2021-03-17 01:15:50,271 DEBUG - [chan 1] EOF received (1)
2021-03-17 01:15:50,271 DEBUG - [chan 1] EOF sent (1)
2021-03-17 01:15:50,273 DEBUG - EOF in transport thread
2021-03-17 01:15:50,273 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 01:15:50,273 DEBUG - Secsh channel 2 opened.
2021-03-17 01:15:50,324 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 01:15:50,378 DEBUG - [chan 2] EOF received (2)
2021-03-17 01:15:50,379 DEBUG - [chan 2] EOF sent (2)
2021-03-17 01:15:50,380 DEBUG - EOF in transport thread
2021-03-17 02:01:27,073 DEBUG - starting thread (client mode): 0xc5b79fd0L
2021-03-17 02:01:27,073 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 02:01:27,085 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 02:01:27,085 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 02:01:27,088 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 02:01:27,089 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 02:01:27,089 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 02:01:27,089 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 02:01:27,089 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 02:01:27,089 DEBUG - Compression agreed: none
2021-03-17 02:01:27,143 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 02:01:27,144 DEBUG - Switch to new keys ...
2021-03-17 02:01:27,175 DEBUG - Adding ssh-ed25519 host key for [103.80.27.108]:28032: fb679dcdfda01a6424c0563de3f822e1
2021-03-17 02:01:27,176 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 02:01:27,188 DEBUG - userauth is OK
2021-03-17 02:01:32,220 INFO - Authentication (publickey) successful!
2021-03-17 02:01:32,226 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 02:01:32,230 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-17 02:01:32,230 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-17 02:01:32,230 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 02:01:32,272 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 02:01:32,272 DEBUG - Secsh channel 0 opened.
2021-03-17 02:01:32,297 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 02:01:32,303 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 02:01:32,303 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 02:01:32,307 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 02:01:32,307 DEBUG - Secsh channel 1 opened.
2021-03-17 02:01:32,313 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 02:01:37,643 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 02:01:37,645 DEBUG - [chan 1] EOF received (1)
2021-03-17 02:01:37,645 DEBUG - [chan 1] EOF sent (1)
2021-03-17 02:01:37,647 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 02:01:37,647 DEBUG - Secsh channel 2 opened.
2021-03-17 02:01:37,697 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 02:01:37,712 DEBUG - [chan 2] EOF received (2)
2021-03-17 02:01:37,713 DEBUG - [chan 2] EOF sent (2)
2021-03-17 02:01:37,714 DEBUG - EOF in transport thread
2021-03-17 02:01:45,784 DEBUG - starting thread (client mode): 0xc5b79e90L
2021-03-17 02:01:45,784 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 02:02:00,790 ERROR - Exception: Error reading SSH protocol banner
2021-03-17 02:02:00,792 ERROR - Traceback (most recent call last):
2021-03-17 02:02:00,792 ERROR -   File "/app/argus_final/venv/lib/python2.7/site-packages/paramiko/transport.py", line 2039, in run
2021-03-17 02:02:00,792 ERROR -     self._check_banner()
2021-03-17 02:02:00,792 ERROR -   File "/app/argus_final/venv/lib/python2.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
2021-03-17 02:02:00,792 ERROR -     "Error reading SSH protocol banner" + str(e)
2021-03-17 02:02:00,792 ERROR - SSHException: Error reading SSH protocol banner
2021-03-17 02:02:00,792 ERROR - 
2021-03-17 02:10:24,600 DEBUG - starting thread (client mode): 0xc85d1e90L
2021-03-17 02:10:24,600 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 02:10:24,641 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 02:10:24,641 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 02:10:24,647 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 02:10:24,647 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 02:10:24,647 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 02:10:24,647 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 02:10:24,647 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 02:10:24,647 DEBUG - Compression agreed: none
2021-03-17 02:10:24,671 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 02:10:24,672 DEBUG - Switch to new keys ...
2021-03-17 02:10:24,701 DEBUG - Adding ssh-ed25519 host key for [58.64.177.145]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-17 02:10:24,703 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 02:10:24,716 DEBUG - userauth is OK
2021-03-17 02:10:24,789 INFO - Authentication (publickey) successful!
2021-03-17 02:10:24,805 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-17 02:10:24,829 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-17 02:10:24,829 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-17 02:10:24,829 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-17 02:10:24,871 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-17 02:10:24,871 DEBUG - Secsh channel 0 opened.
2021-03-17 02:10:24,912 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 02:10:24,922 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-17 02:10:24,923 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-17 02:10:24,926 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-17 02:10:24,926 DEBUG - Secsh channel 1 opened.
2021-03-17 02:10:24,937 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-17 02:10:31,945 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-17 02:10:31,947 DEBUG - [chan 1] EOF received (1)
2021-03-17 02:10:31,947 DEBUG - [chan 1] EOF sent (1)
2021-03-17 02:10:31,949 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-17 02:10:31,949 DEBUG - Secsh channel 2 opened.
2021-03-17 02:10:32,002 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-17 02:10:32,065 DEBUG - [chan 2] EOF received (2)
2021-03-17 02:10:32,066 DEBUG - [chan 2] EOF sent (2)
2021-03-17 02:10:32,067 DEBUG - EOF in transport thread
2021-03-17 03:08:06,937 DEBUG - starting thread (client mode): 0xc6ba8990L
2021-03-17 03:08:06,937 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-17 03:08:06,973 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-17 03:08:06,974 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-17 03:08:06,979 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-17 03:08:06,979 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-17 03:08:06,980 DEBUG - HostKey agreed: ssh-ed25519
2021-03-17 03:08:06,980 DEBUG - Cipher agreed: aes128-ctr
2021-03-17 03:08:06,980 DEBUG - MAC agreed: hmac-sha2-256
2021-03-17 03:08:06,980 DEBUG - Compression agreed: none
2021-03-17 03:08:07,006 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-17 03:08:07,007 DEBUG - Switch to new keys ...
2021-03-17 03:08:07,039 DEBUG - Adding ssh-ed25519 host key for [58.64.177.152]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-17 03:08:07,041 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-17 03:08:07,051 DEBUG - userauth is OK
2021-03-17 03:08:07,115 INFO - Authentication (publickey) failed.
2021-03-17 03:09:06,976 DEBUG - EOF in transport thread
2021-03-17 10:00:45,227 ERROR - Internal Server Error: /puppet/acc-autopay_ftp/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/puppet/views.py", line 177, in post
    nonstandard_puppet_log(hostgroup, request.user.username, [result[1]], activity_type='CREATE')
  File "/app/argus_final/app/argus/puppet/lib/puppet_logger.py", line 20, in nonstandard_puppet_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1073-1078: ordinal not in range(128)
2021-03-17 12:19:22,220 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 228-230: ordinal not in range(128)
2021-03-17 17:20:40,703 ERROR - Internal Server Error: /esync/acc-midpay_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 206-207: ordinal not in range(128)
2021-03-18 00:35:57,442 DEBUG - starting thread (client mode): 0xc8589d50L
2021-03-18 00:35:57,442 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-18 00:35:57,485 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-18 00:35:57,485 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-18 00:35:57,497 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-18 00:35:57,497 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-18 00:35:57,497 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-18 00:35:57,497 DEBUG - Cipher agreed: aes128-ctr
2021-03-18 00:35:57,498 DEBUG - MAC agreed: hmac-sha2-256
2021-03-18 00:35:57,498 DEBUG - Compression agreed: none
2021-03-18 00:35:57,508 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-18 00:35:57,509 DEBUG - Switch to new keys ...
2021-03-18 00:35:57,511 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.16.4]:28032: 75d1c31170d6257e2001c1129928c81c
2021-03-18 00:35:57,512 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-18 00:35:57,553 DEBUG - userauth is OK
2021-03-18 00:36:02,614 INFO - Authentication (publickey) successful!
2021-03-18 00:36:02,649 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-18 00:36:03,051 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-18 00:36:03,093 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-18 00:36:03,093 DEBUG - Secsh channel 0 opened.
2021-03-18 00:36:03,135 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-18 00:36:03,147 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-18 00:36:03,148 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-18 00:36:03,158 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-18 00:36:03,159 DEBUG - Secsh channel 1 opened.
2021-03-18 00:36:03,182 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-18 00:36:20,205 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-18 00:36:20,208 DEBUG - [chan 1] EOF received (1)
2021-03-18 00:36:20,209 DEBUG - [chan 1] EOF sent (1)
2021-03-18 00:36:20,210 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-18 00:36:20,210 DEBUG - Secsh channel 2 opened.
2021-03-18 00:36:20,257 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-18 00:36:20,493 DEBUG - [chan 2] EOF received (2)
2021-03-18 00:36:20,494 DEBUG - [chan 2] EOF sent (2)
2021-03-18 00:36:20,495 DEBUG - EOF in transport thread
2021-03-18 09:36:33,662 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 237-239: ordinal not in range(128)
2021-03-18 09:38:48,653 ERROR - Internal Server Error: /domains/ssladded
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view domains.views.add_sslchecker didn't return an HttpResponse object. It returned None instead.
2021-03-18 09:42:31,633 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 252-254: ordinal not in range(128)
2021-03-18 10:11:36,400 ERROR - Internal Server Error: /esync/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 237-239: ordinal not in range(128)
2021-03-18 10:43:54,505 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-18 14:03:55,726 ERROR - Internal Server Error: /esync/acc-midpay_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 297-303: ordinal not in range(128)
2021-03-18 14:05:00,091 ERROR - Internal Server Error: /esync/acc-midpay_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 276-282: ordinal not in range(128)
2021-03-18 15:33:27,610 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 243-245: ordinal not in range(128)
2021-03-18 15:55:01,805 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 346-347: ordinal not in range(128)
2021-03-18 16:01:32,070 ERROR - Internal Server Error: /esync/om-fpms_pms_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 344-345: ordinal not in range(128)
2021-03-18 18:52:49,163 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2021-03-19 15:06:21,582 ERROR - Internal Server Error: /esync/acc-midpay_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 264-267: ordinal not in range(128)
2021-03-19 15:35:56,078 ERROR - Internal Server Error: /puppet/om-test_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/puppet/views.py", line 177, in post
    nonstandard_puppet_log(hostgroup, request.user.username, [result[1]], activity_type='CREATE')
  File "/app/argus_final/app/argus/puppet/lib/puppet_logger.py", line 20, in nonstandard_puppet_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 332-333: ordinal not in range(128)
2021-03-20 07:43:07,004 DEBUG - starting thread (client mode): 0xc4d90b90L
2021-03-20 07:43:07,004 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-20 07:43:07,043 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.6.1
2021-03-20 07:43:07,043 INFO - Connected (version 2.0, client OpenSSH_6.6.1)
2021-03-20 07:43:07,051 DEBUG - kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-20 07:43:07,052 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-20 07:43:07,052 DEBUG - HostKey agreed: ssh-ed25519
2021-03-20 07:43:07,052 DEBUG - Cipher agreed: aes128-ctr
2021-03-20 07:43:07,052 DEBUG - MAC agreed: hmac-sha2-256
2021-03-20 07:43:07,052 DEBUG - Compression agreed: none
2021-03-20 07:43:07,075 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-20 07:43:07,075 DEBUG - Switch to new keys ...
2021-03-20 07:43:07,106 DEBUG - Adding ssh-ed25519 host key for [46.8.198.14]:28032: 649bfb2ade50b259183468bcc4a641be
2021-03-20 07:43:07,107 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-20 07:43:07,122 DEBUG - userauth is OK
2021-03-20 07:43:12,190 INFO - Authentication (publickey) successful!
2021-03-20 07:43:12,213 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-20 07:43:12,246 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-20 07:43:12,289 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-20 07:43:12,290 DEBUG - Secsh channel 0 opened.
2021-03-20 07:43:12,325 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 07:43:12,333 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 07:43:12,333 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-20 07:43:12,338 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-20 07:43:12,338 DEBUG - Secsh channel 1 opened.
2021-03-20 07:43:12,351 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-20 07:43:20,744 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-20 07:43:20,746 DEBUG - [chan 1] EOF received (1)
2021-03-20 07:43:20,747 DEBUG - [chan 1] EOF sent (1)
2021-03-20 07:43:20,750 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-20 07:43:20,750 DEBUG - Secsh channel 2 opened.
2021-03-20 07:43:20,800 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-20 07:43:20,862 DEBUG - [chan 2] EOF received (2)
2021-03-20 07:43:20,862 DEBUG - [chan 2] EOF sent (2)
2021-03-20 07:43:20,864 DEBUG - EOF in transport thread
2021-03-20 07:46:33,592 DEBUG - starting thread (client mode): 0xc3fe0710L
2021-03-20 07:46:33,593 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-20 07:46:33,614 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-20 07:46:33,615 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-20 07:46:33,618 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-20 07:46:33,619 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-20 07:46:33,619 DEBUG - HostKey agreed: ssh-ed25519
2021-03-20 07:46:33,619 DEBUG - Cipher agreed: aes128-ctr
2021-03-20 07:46:33,619 DEBUG - MAC agreed: hmac-sha2-256
2021-03-20 07:46:33,619 DEBUG - Compression agreed: none
2021-03-20 07:46:33,674 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-20 07:46:33,675 DEBUG - Switch to new keys ...
2021-03-20 07:46:33,694 DEBUG - Adding ssh-ed25519 host key for [103.40.8.233]:28032: ea76ce94b93e3e0b925af7530a54fa6f
2021-03-20 07:46:33,695 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-20 07:46:33,721 DEBUG - userauth is OK
2021-03-20 07:46:33,783 INFO - Authentication (publickey) successful!
2021-03-20 07:46:33,797 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-20 07:46:33,802 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-20 07:46:33,802 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-20 07:46:33,802 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-20 07:46:33,845 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-20 07:46:33,846 DEBUG - Secsh channel 0 opened.
2021-03-20 07:46:33,869 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 07:46:33,876 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 07:46:33,877 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-20 07:46:33,881 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-20 07:46:33,881 DEBUG - Secsh channel 1 opened.
2021-03-20 07:46:33,891 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-20 07:46:33,912 DEBUG - [chan 1] EOF received (1)
2021-03-20 07:46:33,912 DEBUG - [chan 1] EOF sent (1)
2021-03-20 07:46:33,913 DEBUG - EOF in transport thread
2021-03-20 07:46:33,927 DEBUG - starting thread (client mode): 0xc4da60d0L
2021-03-20 07:46:33,927 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-20 07:46:33,942 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-20 07:46:33,942 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-20 07:46:33,946 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-20 07:46:33,946 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-20 07:46:33,947 DEBUG - HostKey agreed: ssh-ed25519
2021-03-20 07:46:33,947 DEBUG - Cipher agreed: aes128-ctr
2021-03-20 07:46:33,947 DEBUG - MAC agreed: hmac-sha2-256
2021-03-20 07:46:33,947 DEBUG - Compression agreed: none
2021-03-20 07:46:34,001 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-20 07:46:34,002 DEBUG - Switch to new keys ...
2021-03-20 07:46:34,029 DEBUG - Adding ssh-ed25519 host key for [103.40.8.233]:28032: ea76ce94b93e3e0b925af7530a54fa6f
2021-03-20 07:46:34,030 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-20 07:46:34,049 DEBUG - userauth is OK
2021-03-20 07:46:34,107 INFO - Authentication (publickey) successful!
2021-03-20 07:46:34,132 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-20 07:46:34,136 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-20 07:46:34,136 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-20 07:46:34,137 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-20 07:46:34,179 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-20 07:46:34,179 DEBUG - Secsh channel 0 opened.
2021-03-20 07:46:34,203 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 07:46:34,209 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 07:46:34,210 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-20 07:46:34,214 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-20 07:46:34,215 DEBUG - Secsh channel 1 opened.
2021-03-20 07:46:34,225 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-20 07:46:34,253 DEBUG - [chan 1] EOF received (1)
2021-03-20 07:46:34,253 DEBUG - [chan 1] EOF sent (1)
2021-03-20 07:46:34,254 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-20 07:46:34,301 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-20 07:46:34,301 DEBUG - Secsh channel 2 opened.
2021-03-20 07:46:34,325 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-20 07:46:34,351 DEBUG - [chan 2] EOF received (2)
2021-03-20 07:46:34,351 DEBUG - [chan 2] EOF sent (2)
2021-03-20 07:46:34,353 DEBUG - [chan 3] Max packet in: 32768 bytes
2021-03-20 07:46:34,399 DEBUG - [chan 3] Max packet out: 32768 bytes
2021-03-20 07:46:34,399 DEBUG - Secsh channel 3 opened.
2021-03-20 07:46:34,424 DEBUG - [chan 3] Sesch channel 3 request ok
2021-03-20 07:46:34,453 DEBUG - [chan 3] EOF received (3)
2021-03-20 07:46:34,453 DEBUG - [chan 3] EOF sent (3)
2021-03-20 07:46:34,454 DEBUG - EOF in transport thread
2021-03-20 21:06:00,188 DEBUG - starting thread (client mode): 0xc4e03d50L
2021-03-20 21:06:00,188 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-20 21:06:00,225 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-20 21:06:00,225 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-20 21:06:00,239 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-20 21:06:00,239 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-20 21:06:00,239 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-20 21:06:00,239 DEBUG - Cipher agreed: aes128-ctr
2021-03-20 21:06:00,239 DEBUG - MAC agreed: hmac-sha2-256
2021-03-20 21:06:00,239 DEBUG - Compression agreed: none
2021-03-20 21:06:00,247 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-20 21:06:00,248 DEBUG - Switch to new keys ...
2021-03-20 21:06:00,253 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.19.196]:28032: eebe5f304e31a324d4aac75716449e42
2021-03-20 21:06:00,255 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-20 21:06:00,291 DEBUG - userauth is OK
2021-03-20 21:06:05,374 INFO - Authentication (publickey) successful!
2021-03-20 21:06:05,392 DEBUG - EOF in transport thread
2021-03-20 21:06:08,400 DEBUG - starting thread (client mode): 0xc497ced0L
2021-03-20 21:06:08,401 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-20 21:06:08,432 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_6.4
2021-03-20 21:06:08,432 INFO - Connected (version 2.0, client OpenSSH_6.4)
2021-03-20 21:06:08,444 DEBUG - kex algos:[u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-20 21:06:08,444 DEBUG - Kex agreed: ecdh-sha2-nistp256
2021-03-20 21:06:08,445 DEBUG - HostKey agreed: ecdsa-sha2-nistp256
2021-03-20 21:06:08,445 DEBUG - Cipher agreed: aes128-ctr
2021-03-20 21:06:08,445 DEBUG - MAC agreed: hmac-sha2-256
2021-03-20 21:06:08,445 DEBUG - Compression agreed: none
2021-03-20 21:06:08,453 DEBUG - kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2021-03-20 21:06:08,454 DEBUG - Switch to new keys ...
2021-03-20 21:06:08,468 DEBUG - Adding ecdsa-sha2-nistp256 host key for [103.56.19.196]:28032: eebe5f304e31a324d4aac75716449e42
2021-03-20 21:06:08,470 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-20 21:06:08,498 DEBUG - userauth is OK
2021-03-20 21:06:13,576 INFO - Authentication (publickey) successful!
2021-03-20 21:06:13,607 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-20 21:06:14,188 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-20 21:06:14,230 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-20 21:06:14,231 DEBUG - Secsh channel 0 opened.
2021-03-20 21:06:14,254 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 21:06:14,264 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-20 21:06:14,264 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-20 21:06:14,273 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-20 21:06:14,273 DEBUG - Secsh channel 1 opened.
2021-03-20 21:06:14,288 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-20 21:06:27,400 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-20 21:06:27,402 DEBUG - [chan 1] EOF received (1)
2021-03-20 21:06:27,402 DEBUG - [chan 1] EOF sent (1)
2021-03-20 21:06:27,404 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-20 21:06:27,404 DEBUG - Secsh channel 2 opened.
2021-03-20 21:06:27,449 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-20 21:06:27,480 DEBUG - [chan 2] EOF received (2)
2021-03-20 21:06:27,481 DEBUG - [chan 2] EOF sent (2)
2021-03-20 21:06:27,482 DEBUG - EOF in transport thread
2021-03-21 16:52:54,510 DEBUG - (james.cadelina) - Successfully loaded and updated table
2021-03-22 05:56:07,952 DEBUG - (lyden.reyes) - Successfully loaded and updated table
2021-03-22 05:56:38,050 DEBUG - (lyden.reyes) - Successfully loaded and updated table
2021-03-22 05:57:21,594 DEBUG - (lyden.reyes) - Successfully loaded and updated table
2021-03-22 08:34:07,708 ERROR - Internal Server Error: /esync/om-clientgamecalled_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-22 08:37:56,449 ERROR - Internal Server Error: /esync/om-clientgamecalled_nginx/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 169, in get
    context['keys'] = parse_standard_config(context['content'])
  File "/app/argus_final/app/argus/esync/lib/nginx_processor.py", line 11, in parse_standard_config
    rConfig = nginx.loads(config).as_dict
  File "/app/argus_final/venv/lib/python2.7/site-packages/nginx.py", line 402, in loads
    m = re.compile(r'^\s*events\s*{', re.S).search(data[index:])
TypeError: 'bool' object has no attribute '__getitem__'
2021-03-22 09:31:17,218 DEBUG - starting thread (client mode): 0xc4fc6f10L
2021-03-22 09:31:17,218 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2021-03-22 09:31:17,233 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-03-22 09:31:17,233 INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-03-22 09:31:17,236 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2021-03-22 09:31:17,237 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-03-22 09:31:17,237 DEBUG - HostKey agreed: ssh-ed25519
2021-03-22 09:31:17,237 DEBUG - Cipher agreed: aes128-ctr
2021-03-22 09:31:17,237 DEBUG - MAC agreed: hmac-sha2-256
2021-03-22 09:31:17,237 DEBUG - Compression agreed: none
2021-03-22 09:31:17,289 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-03-22 09:31:17,290 DEBUG - Switch to new keys ...
2021-03-22 09:31:17,320 DEBUG - Adding ssh-ed25519 host key for [154.209.4.56]:28032: fb679dcdfda01a6424c0563de3f822e1
2021-03-22 09:31:17,321 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2021-03-22 09:31:17,335 DEBUG - userauth is OK
2021-03-22 09:31:17,393 INFO - Authentication (publickey) successful!
2021-03-22 09:31:17,395 DEBUG - [chan 0] Max packet in: 32768 bytes
2021-03-22 09:31:17,417 DEBUG - Received global request "hostkeys-00@openssh.com"
2021-03-22 09:31:17,418 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-03-22 09:31:17,418 DEBUG - Debug msg: Adding to environment: NAME=argus
2021-03-22 09:31:17,460 DEBUG - [chan 0] Max packet out: 32768 bytes
2021-03-22 09:31:17,461 DEBUG - Secsh channel 0 opened.
2021-03-22 09:31:17,467 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-22 09:31:17,477 DEBUG - [chan 0] Sesch channel 0 request ok
2021-03-22 09:31:17,479 DEBUG - [chan 1] Max packet in: 32768 bytes
2021-03-22 09:31:17,482 DEBUG - [chan 1] Max packet out: 32768 bytes
2021-03-22 09:31:17,483 DEBUG - Secsh channel 1 opened.
2021-03-22 09:31:17,494 DEBUG - [chan 1] Sesch channel 1 request ok
2021-03-22 09:31:24,329 DEBUG - [chan 2] Max packet in: 32768 bytes
2021-03-22 09:31:24,331 DEBUG - [chan 1] EOF received (1)
2021-03-22 09:31:24,331 DEBUG - [chan 1] EOF sent (1)
2021-03-22 09:31:24,334 DEBUG - [chan 2] Max packet out: 32768 bytes
2021-03-22 09:31:24,334 DEBUG - Secsh channel 2 opened.
2021-03-22 09:31:24,383 DEBUG - [chan 2] Sesch channel 2 request ok
2021-03-22 09:31:24,397 DEBUG - [chan 2] EOF received (2)
2021-03-22 09:31:24,398 DEBUG - [chan 2] EOF sent (2)
2021-03-22 09:31:24,399 DEBUG - EOF in transport thread
